---
# Handler to handle common notifications. Handlers are called by other plays.
# See http://ansible.cc/docs/playbooks.html for more information about handlers.

- name: restart supervisord
  service: name=supervisor state=restarted

- name: insserv supervisord
  shell: /usr/lib/insserv/insserv supervisor
